services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - ./pihole/.env
    environment:
      WEB_PORT: ${PORT:-80}
      PIHOLE_UID: ${UID:-1000}
      PIHOLE_GID: ${GID:-1000}
      # TODO Remove
      # DNSMASQ_LISTENING: all
      # ServerIP: 192.168.1.130  # IP del host donde corre Docker
  
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
      - ./pihole/static-entries:/etc/custom.d/01-static-entries:ro
      - ./pihole/adlists:/etc/custom.d/02-adlists:ro
    labels:
      - "traefik.enable=true"

      # Router para LAN (Let's Encrypt)
      - "traefik.http.routers.pihole-lan.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pihole-lan.entrypoints=websecure"
      - "traefik.http.routers.pihole-lan.tls=true"
      - "traefik.http.routers.pihole-lan.tls.certresolver=letsencrypt-cloudflare"
      - "traefik.http.routers.pihole-lan.service=pihole-lan-service"
      - "traefik.http.services.pihole-lan-service.loadbalancer.server.port=${PORT:-80}"
      - "traefik.http.routers.pihole-lan.middlewares=redirect-pihole@file"
    networks:
      traefik-network:
        ipv4_address: 172.20.0.3
    restart: unless-stopped
    # https://docs.pi-hole.net/docker/#note-on-capabilities
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE


volumes:
  pihole_data:
    external: false
  dnsmasq_data:
    external: false
    

