tls:
  options:
    cloudflare:
      # minVersion: VersionTLS12
      # cipherSuites:
      #   - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      #   - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      #   - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      #   - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384      
      sniStrict: false

  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/origin.pem"
        keyFile: "/etc/traefik/certs/origin.key"