services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    env_file:
      - ./services/homepage/.env
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN:-}
    labels:
      - "traefik.enable=true"

      # Router para LAN (Let's Encrypt)
      - "traefik.http.routers.homepage-lan.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.homepage-lan.entrypoints=websecure"
      - "traefik.http.routers.homepage-lan.tls=true"
      - "traefik.http.routers.homepage-lan.tls.certresolver=letsencrypt-cloudflare"
      - "traefik.http.routers.homepage-lan.service=homepage-lan-service"
      - "traefik.http.services.homepage-lan-service.loadbalancer.server.port=${PORT:-3000}"
    volumes:
      - ./services/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    networks:
      traefik-network:
        ipv4_address: 172.20.0.30
    dns:
      - 172.20.0.3
    restart: unless-stopped

